language: php
php:
  - '7.1'

services:
    - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - mysql -e 'CREATE DATABASE brainly;'
install:
    - composer update --prefer-source $COMPOSER_FLAGS
    - composer global require hirak/prestissimo

script:
    - phpunit --coverage-text -c phpunit.xml.dist
    - ./vendor/bin/codecept run
