language: php
php:
  - '7.1'

services:
    - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

install: composer update --prefer-source $COMPOSER_FLAGS

script:
    - phpunit --coverage-text -c phpunit.xml.dist
    - ./vendor/bin/codecept run
