questions:
    type: rest
    resource: Brainly\UserInterface\Symfony\AppBundle\Controller\QuestionsController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc