imports:
    - { resource: services/tactician.yml }
    - { resource: services/question.yml }
    - { resource: services/answer.yml }

parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Brainly\Application\:
        resource: '../../src/Application/*'
        exclude: '../../src/Application/Command/*'

    Brainly\UserInterface\:
        resource: '../../src/UserInterface/*'

    Brainly\Infrastructure\:
        resource: '../../src/Infrastructure/*'

    Brainly\UserInterface\Symfony\AppBundle\Controller\:
        resource: '../../src/UserInterface/Symfony/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
