services:
    brainly.param_coverter.uuid_answer:
        class: Brainly\UserInterface\Symfony\AppBundle\ParamConverter\UuidAnswerParamConverter
        arguments:
            - '@Brainly\Infrastructure\Domain\AnswersRepository'
        tags:
            - { name: request.param_converter, priority: 1, converter: question_id_string }
